# Generated by Django 4.1.7 on 2024-09-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchtool', '0017_authorenglish_addrequest_subjects_addrequest_summary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addrequest',
            name='authorEnglish2',
        ),
        migrations.RemoveField(
            model_name='addrequest',
            name='requestid',
        ),
        migrations.RemoveField(
            model_name='addrequest',
            name='uid2',
        ),
        migrations.RemoveField(
            model_name='addrequest',
            name='yearCreated',
        ),
    ]
